---
sudo: required
dist: trusty
language: python
python: "2.7"

env:
  - SITE=test.yml
  - SITE=test-phpunit.yml

before_install:
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Download dependencies
  - ansible-galaxy install telusdigital.slack telusdigital.postgresql telusdigital.mariadb
  - ansible-galaxy install telusdigital.nodejs telusdigital.upstart telusdigital.php telusdigital.yo-dawg

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook -i tests/inventory tests/$SITE --syntax-check"

  # Run the role/playbook with ansible-playbook.
  - "ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo"

  # Run the role/playbook in --check mode.
  - "ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo --check"
