---
- include: cleanup.yml
- include: install.yml
- include: configure.yml
- include: listen-with-php.yml
  when: autodeploy_listener == 'php'
- include: listen-with-node.yml
  when: autodeploy_listener == 'node'
